"""
FastAPI wrapper for SatQuery AI's query routing engine.

Exposes:
    POST /query   - Accepts a user question, runs it through
                    process_query() (intent classification +
                    grounded Gemini response), and returns the result.
    GET  /health  - Basic liveness check for load balancers / uptime
                    monitors.

This module is intentionally thin: all business logic (intent
classification, prompt selection, grounding data loading, Gemini
invocation) lives in `query_engine.router`. This file is only
responsible for HTTP concerns - request/response schemas, status
codes, and error handling.
"""

import logging

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from query_engine.router import process_query, classify_intent

# Logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("satquery_ai.api")


# App instance

app = FastAPI(
    title="SatQuery AI",
    description="Query routing and grounded language layer for satellite land cover analysis.",
    version="0.1.0",
)


# Pydantic schemas

class QueryRequest(BaseModel):
    """Request body for POST /query."""

    query: str = Field(
        ...,
        min_length=1,
        description="The user's natural language question about land cover data.",
        examples=["Where is the water body located in this grid?"],
    )


class QueryResponse(BaseModel):
    """Response body for POST /query."""

    result: str = Field(
        ...,
        description="The grounded, evidence-cited answer generated by the LLM, "
        "or a decline message if the query is unsupported / evidence is missing.",
    )
    intent: str | None = Field(
        default=None,
        description="The classified QueryIntent value for this query, if classification succeeded.",
    )


class HealthResponse(BaseModel):
    """Response body for GET /health."""

    status: str = "ok"


# Routes

@app.get("/health", response_model=HealthResponse, tags=["ops"])
def health_check() -> HealthResponse:
    """
    Basic liveness check. Returns 200 with {"status": "ok"} as long as
    the process is up. Does NOT verify downstream Gemini connectivity -
    keep this endpoint fast and dependency-free for load balancer probes.
    """
    return HealthResponse(status="ok")


@app.post("/query", response_model=QueryResponse, tags=["query"])
def query_endpoint(request: QueryRequest) -> QueryResponse:
    """
    Accepts a user query, routes it through the SatQuery AI pipeline
    (intent classification -> prompt selection -> grounded Gemini call),
    and returns the resulting answer along with the classified intent.
    """
    user_query = request.query.strip()

    if not user_query:
        raise HTTPException(status_code=400, detail="Query must not be empty.")

    # Classify separately (in addition to process_query's internal
    # classification) purely so we can surface `intent` in the API
    # response without changing process_query's existing signature.
    # NOTE: If classify_intent becomes non-deterministic or expensive,
    # revisit this - today it's a placeholder that's cheap to call twice.
    try:
        intent = classify_intent(user_query)
        intent_value = str(intent.value) if hasattr(intent, "value") else str(intent)
    except Exception:
        logger.exception("Intent classification failed for query: %r", user_query)
        intent_value = None

    try:
        result = process_query(user_query)
    except FileNotFoundError as e:
        # Grounding facts file missing - a config/deployment issue, not a client error.
        logger.exception("Grounding facts file missing.")
        raise HTTPException(status_code=500, detail=str(e))
    except ValueError as e:
        # Malformed grounding facts JSON - also a server-side config issue.
        logger.exception("Grounding facts file invalid.")
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        # Catch-all for unexpected failures (e.g. Gemini API errors that
        # weren't already caught inside process_query).
        logger.exception("Unexpected error while processing query: %r", user_query)
        raise HTTPException(status_code=502, detail=f"Failed to process query: {e}")

    return QueryResponse(result=result, intent=intent_value)
